### ISSUE TITLE
When the column contains out or range value, it should return nil or the one in option `default`  

### ISSUE THREAD

**Issue by PikachuEXE** [brainspec/enumerize#125]
I have set the `default` option on a new column
The column is a `string` column which is nullable

I expect to see the default value and text but I see `nil`

I am not sure if this is a bug or feature request but putting the default value in code is much better than in migration

If people forgot to set `default`, returning `nil` is fine

**Comment by nashby** [comment]
@PikachuEXE hey, sorry for that super late response but after thinking about it a bit more (like almost 3 years) we decided to leave it as it is right now. The reason behind it is that setting `nil` to the attributes instead of `default` makes more sense in case when you're assigning wrong value. In  case when `nil` is set and you have presence validation your record won't be saved and it's what you want in most cases. Cheers!

**Comment by PikachuEXE** [comment]
OK thx!
