### ISSUE TITLE
Can't access _text or _value after changing it

### ISSUE THREAD

**Issue by Awea** [brainspec/enumerize#166]
I have a model

``` ruby
class Contact
  extend Enumerize
  include ActiveModel::Model

  attr_accessor :subject
  enumerize :subject, in: [:quotation, :informations, :recruitment, :other], default: :quotation
end
```

Then I try to play with it 

```
Contact.new.subject_text
#=> Quotation
Contact.new(subject: 'informations').subject_text
#=> NoMethodError: undefined method `text' for "informations":String
    from /Users/awea/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/enumerize-0.8.0/lib/enumerize/attribute.rb:102:in `subject_text'
```

It's an issue or I'm doing something wrong ?

**Comment by ChristianPeters** [comment]
Thanks for the hint!

@lest @nashby Should this be added to the documentation? If you are using POROs you tend to declare all your attributes using `attr_accessor` and this problem occurs when doing so for enumerized attributes. Could this even be fixed in enumerized so that redundant accessors are no problem?
