### ISSUE TITLE
Validates Inclusion for Symbols

### ISSUE THREAD

**Issue by RickCSong** [brainspec/enumerize#207]
Hey!  It seems that Enumerize doesn't work on validating inclusion if the field is a symbol?  I'm not sure if this is intended behavior, but it would be great to have!  

```ruby
class Foo < ActiveRecord::Base
  extend Enumerize

  STATUSES = [:pending, :success, :failed]

  enumerize :status, STATUSES

  validates :status, inclusion: { in: STATUSES }, if: :something_is_true
end
```

Thanks!

**Comment by RickCSong** [comment]
Would it be possible to have an option for enumerize to convert everything to symbols? 

Maybe something like..

```
enumerize :status, STATUSES, symbolize: true
```

I would be happy to make a PR for that if its alright

**Comment by kreintjes** [comment]
+1

I think this issue is related to https://github.com/brainspec/enumerize/issues/32. I also tend to use symbols for my enum values, and would like to compare them as such. Of course I can use the boolean methods like `role.admin?`, but this is not always possible. For example in a case statement, or if you want to define CanCan abilities with a role. You then need to set the allowed roles using strings, instead of symbols, which was possible with symbolize.

**Comment by marcalc** [comment]
+1 

This would be great for a project which I need to migrate from symbolize.

Anyone has had any success with this?

**Comment by nashby** [comment]
Hey guys! Sorry for the late response but we won't work on option to convert everything to symbols since it's not that easy to make it work since we use `Enumerize::Value` as enum values and it's inherited from `String` class. 

@RickCSong there's no need to use inclusion validation here since you can't assign something that is not in the `STATUSES` list by default. So presence validation would work for you.
