### ISSUE TITLE
Ability to disable validation

### ISSUE THREAD

**Issue by romansklenar** [brainspec/enumerize#212]
Hello, does Enumerize has an option to bypass validation on enumerized attribute?
Would you consider to add it if you'd find it useful or if I'd provide PR with this feature?

**Comment by nashby** [comment]
@romansklenar hey, can you please elaborate on why do you need this feature? Any specific use-case? Thank you!

**Comment by romansklenar** [comment]
@nashby For example when I want to add custom validation for attribute (message or even logic).

**Comment by nashby** [comment]
I think you can just override [`_validate_enumerized_attributes`](https://github.com/brainspec/enumerize/blob/c10b8b85bae4fbe7c60d8f7c8cb1d0f62507d221/lib/enumerize/base.rb#L81) method in your model for doing that. @lest do you think it's ok or we need to implement something special for that?

**Comment by lest** [comment]
Overriding `_validate_enumerized_attributes` looks like a way to disable the default behavior.

@romansklenar Also I'm not against adding a new option if you would like to use it instead of overriding that method. I would appreciate a pull request in this case. We can check it [only in a single place](https://github.com/brainspec/enumerize/blob/c10b8b85bae4fbe7c60d8f7c8cb1d0f62507d221/lib/enumerize/base.rb#L7), so it will have a simple implementation.

Thanks!

**Comment by nashby** [comment]
closing this fro now. @romansklenar feel free to send a PR if you still need this feature, thanks!

**Comment by chumakoff** [comment]
Having the same problem. I am surprised there is no option to skip the validation. I cannot allow the column to have NULL value. Is there really no option, maybe something has changed since Dec 13, 2015?
