### ISSUE TITLE
Allowing proc's on :in param

### ISSUE THREAD

**Issue by oswaldoferreira** [brainspec/enumerize#248]
There's any interest at allowing execution of a proc on `:in` param?

Example:

```ruby
# Any model.rb
enumerize :option, in: -> (model_instance) { model_instance.options }

def options
  { foo: 'foo', bar: 'bar' }
end
```

**Comment by lest** [comment]
Unfortunately, I don't think that this is possible (or at least feasible enough) because there is `Model.option.options` and `Model.option.values` methods available that should work without instantiating a model instance.

Could you please provide a use case for this feature so we can consider how it can be approached?

**Comment by oswaldoferreira** [comment]
@lest My bad, after scanning down the doc's I found out that it's not really necessary on my case. Thanks for the help.
