### ISSUE TITLE
Boolean array does not work on Rails 5.1

### ISSUE THREAD

**Issue by DIGITALSQUAD** [brainspec/enumerize#276]
On Rails 5.0.1 this validation and enumerize has been working fine.
```
class Variant < ApplicationRecord
  extend Enumerize
  validates :publied, presenrce: true, inclusion: { in: %w(true false) }
  enumerize :published, in: %w(true false)
end
```

However after upgraded to Rails 5.1, enumerize tries to insert boolean as string('true') and it cause error below.
```
ActiveRecord::StatementInvalid:
       Mysql2::Error: Incorrect integer value: 'true' for column 'published' at row 1: INSERT INTO `variants` (`published`) VALUES ('true')
```
Validation works fine since I changed `validates :published,presence: true, inclusion: { in: [true, false] }`
However enumerize does not work though changed as the same  `enumerize :published, in: [true, false]`

How to fix it?

**Comment by lest** [comment]
Hi @DIGITALSQUAD 

Enumerize assumes that values are strings when an array is passed as the `:in` option. It is possible to pass a hash which is used, for example, to store integers in the DB instead of strings. Enumerize is not supposed to work with boolean values, but maybe it can work with booleans too (I haven't tested it):

```
enumerize :published, in: {true: true, false: false}
```

However, I wouldn't recommend using enumerize for boolean columns. Is there any specific enumerize feature that makes it simpler to use enumerize in your example?

**Comment by DIGITALSQUAD** [comment]
Thanks for your reply @lest 
Unfortunately your code does't work but I got that not recommended for boolean columns. I guessed that it is for strings.
The reason why I tried is that it's useful for FormBuilder like options.    
`f.select :published, Variant.published.options`
