### ISSUE TITLE
Using Postgres's Enumerated Types? 

### ISSUE THREAD

**Issue by pelted** [brainspec/enumerize#283]
Since Rails enum only maps to integers I've used Enumerize a few times with good success. Is there any advantage or otherwise to using custom enum types defined in PG along side Enumerize? 

Edge docs have [this reference](http://edgeguides.rubyonrails.org/active_record_postgresql.html#enumerated-types) to using PG's enumerated types with a string field.

**Comment by lest** [comment]
Since enum types are mapped as normal text columns there should be nothing that prevents enumerize from working with them.

I see a benefit in enforcing the allowed list of values on the DB level when using PG enum types. Enumerize provides i18n support and useful integrations with form builder libraries. However, enumerize doesn't support extracting the list of enum values from the column definition (and I suppose it's not so easy to do since Rails maps enums as strings), so the downside is that the list of values needs to be specified twice (in the DB migration and in the model itself).
