### ISSUE TITLE
Allowing proc's on :in params

### ISSUE THREAD

**Issue by nineten** [brainspec/enumerize#287]
#248 revisiting this
I recently encountered a use case for such a feature.
For example if we were to have a dynamic array that may change, then enumerize will prevent the new values of the array from being valid.
[`validates_inclusion_of`](https://apidock.com/rails/v3.1.0/ActiveModel/Validations/HelperMethods/validates_inclusion_of) in rails 3.1 and above supports using proc and lambda

```
# example: validates where BookType.list is a cached array of book_types that can be updated
validates :book_type, inclusion: { in: proc { BookType.list } }
```

**Comment by nashby** [comment]
Hey, @nineten! Thanks for opening issue about that but it's not the feature we plan to support in the near future since we think that the main advantage of using enumerize is when your enumerated values are static so you can use features like i18n, predicates, scopes and so on.

**Comment by kreintjes** [comment]
+1 for this. We also have a model with an attribute for which the options can differ for each instance (in our case they are determined by an association). We would like to be able to dynamically set the options, e.g. with a proc, like this:

```ruby
class Vehicle
  belongs_to :vehicle_type

  enumerize :model, in: -> (vehicle) { vehicle.vehicle_type.available_models }
end
```

For anyone looking for a workaround, this works:

```ruby
class Vehicle
  belongs_to :vehicle_type

  validates :model, inclusion: { in: -> (vehicle) { vehicle.vehicle_type.available_models } }

  enumerize :model, in: ALL_MODELS, skip_validations: true
end

# And use it in forms like this:
f.input :model, collection: Vehicle.model.options(only: f.object.vehicle_type.available_models)
```

But if feels somewhat cumbersome. Being able to use a proc in the enumerize definition directly, would be nice, although it would require a slightly different API for some methods (e.g. `f.object.enumerized_attributes[:model].options` instead of `Vehicle.enumerized_attributes[:model].options`).
