### ISSUE TITLE
Incorrect comparison when Symbols are used at L.H.S.

### ISSUE THREAD

**Issue by ashish91** [brainspec/enumerize#331]
When an enumerated attribute is compared with a symbol, it works when the symbol is at R.H.S.

```
[1] pry(main)> Delivery.last.state == :booked
  Delivery Load (1.0ms)  SELECT  "deliveries".* FROM "deliveries"  ORDER BY "deliveries"."id" DESC LIMIT 1
=> true
```

However it doesn't work when symbol is used at L.H.S. This is because we've overridden `==` method in `Enumerize::Value` class. In this case we called `==` on a Symbol class which doesn't work.

```
[2] pry(main)> :booked == Delivery.last.state
  Delivery Load (1.4ms)  SELECT  "deliveries".* FROM "deliveries"  ORDER BY "deliveries"."id" DESC LIMIT 1
=> false
```

To fix this I've monkey patched the Symbol class itself like this in my app:

```
class Symbol
  def ==(other)
    if other.class.to_s == "Enumerize::Value"
      super(other.to_sym)
    else
      super(other)
    end
  end
end
```

This ensures that a symbol is compared with the symbolized value of the enumerated attribute. I wanted to ask if there's a better way to achieve this. If not maybe we can incorporate something similar into Enumerize gem.

**Comment by mltsy** [comment]
I have the exact same issue, and haven't found a better solution.  I tried to implement it in a way that was not Enumerize-specific:
```ruby
class Symbol
  def ==(other)
    other == self
  end
end
```

But of course, this ends up in a stack overflow when a symbol is compared to itself (checking for the case of comparing a symbol to itself side-steps the problem, but doesn't make it safe: what if another class defined `==` the same way?).  It seems to me that the problem of asymmetrical equality is really a tough challenge in any language that allows it.  See [this excerpt from the book Eloquent Ruby](https://books.google.com/books?id=-s2xL0pVsLUC&pg=PA147&lpg=PA147&dq=asymmetrical+equality+ruby&source=bl&ots=l9J3jyL9L3&sig=ACfU3U1LNHEVJDXR-dYh8xsR4VhQ8ruHUA&hl=en&sa=X&ved=2ahUKEwjGr4bRuIngAhWNxIMKHZnnDngQ6AEwAnoECAcQAQ#v=onepage&q=asymmetrical%20equality%20ruby&f=false)

So probably the safest solution to this is to make the equality symmetrical by either:
1. Monkey-patching Symbol with an Enumerize-specific equality operator, just as you have outlined; or
2. Removing the flexible equality check altogether, and making it equal to only a string (because there is no way to make a Symbol equal to something other than a Symbol)

OR forget the symmetry and 3. Leave it as is and document the asymmetrical equality aspect in the README, since it's a very unexpected feature that can definitely catch a developer off-guard.

As much as I hesitate to include global monkey-patching in a gem, I'm preferential to Option 1, because I really think enum values are best represented as symbols.  Maybe we could maybe it an optional require, or a method you can call in an initializer, like `Enumerize.moneypatch_symbol`?

**Comment by mltsy** [comment]
Ahh, good point!  I suppose using something similar to ActiveSupport's HashWithIndifferentAccess could be another good solution there - for instance, Enumerize could offer a Enumerize::Hash, that works with symbols, strings, or Enumerize::Values.

**Comment by nashby** [comment]
Hey! Sorry for late response. 

We don't have any plans to monkey-patch core Ruby classes to support this feature at this moment. You can always use predicates though:

```
Delivery.last.booked?
```
